modLoader="kotlinforforge"
loaderVersion="${loader_version_range}"
license='${mod_license}'

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets/cartridge/textures/logo.png"
credits="Thanks to thedarkcolour and all the contributors for making Kotlin for Forge"
authors="${mod_authors}"
description='''${mod_description}'''
enumExtensions="META-INF/enumextensions.json"

[[mixins]]
config="cartridge.mixins.minecraft.json"
[[mixins]]
config="cartridge.mixins.carryon.json"

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="curios"
    type="required"
    versionRange="[${curios_version},)"
    ordering="NONE"
    side="BOTH"
[[Dependencies."${mod_id}"]]
    modId="geckolib"
    type="required"
    versionRange="[${geckolib_version},)"
    ordering="NONE"
    side="BOTH"
[[Dependencies."${mod_id}"]]
    modId="carryon"
    type="optional"
    versionRange="[${carryon_version},)"
    ordering="AFTER"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
