name: Generate Data

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to allow for proper merging

      - name: Get Last Commit Message
        id: get_commit_message
        run: |
          echo "LAST_COMMIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Switch to main branch
        run: |
          git checkout main
          git pull origin main

      - name: Merge release into main
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git merge release -s ours
          git branch temp
          git reset --hard release
          git checkout temp -- src/generated
          git reset --soft temp
          NEW_MSG=$(echo "$LAST_COMMIT_MESSAGE" | sed '1s/$/: merge release into main/')
          git commit --amend -m "$NEW_MSG"
          git branch -D temp
          git diff HEAD release

      - name: Run Gradle task
        run: |
          chmod +x ./gradlew
          ./gradlew runData

      - name: Commit changes
        run: |
          git add .
          STATUS_OUTPUT=$(git status --porcelain)
          STATUS_OUTPUT_LENGTH=${#STATUS_OUTPUT}
          if [[ $STATUS_OUTPUT_LENGTH -gt 0 ]]; then
            NEW_MSG=$(echo "$LAST_COMMIT_MESSAGE" | sed '1s/$/: update generated files from release branch/')
            git commit -m "$NEW_MSG"
          else
            echo "No changes to commit."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Check for Release
        id: check_release
        run: |
          FIRST_LINE=$(echo "$LAST_COMMIT_MESSAGE" | head -n 1)
          if echo "$LAST_COMMIT_MESSAGE" | grep -q "^- noRelease$"; then
            echo "create_release=false" >> $GITHUB_ENV
          elif [[ "$FIRST_LINE" =~ ^v([0-9]+(\.[0-9]+)*)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "version=$VERSION" >> $GITHUB_ENV
            echo "create_release=true" >> $GITHUB_ENV
          else
            echo "create_release=false" >> $GITHUB_ENV
          fi

      - name: Run Gradle jar
        if: env.create_release == 'true'
        run: |
          chmod +x ./gradlew
          ./gradlew jar

      - name: Create and push tag
        if: env.create_release == 'true'
        run: |
          git tag v${{ env.version }}
          git push origin v${{ env.version }}

      - name: Create GitHub Release
        if: env.create_release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.version }}"
          name: "Release v${{ env.version }}"
          files: build/libs/cartridge-${{ env.version }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload To Curseforge
        if: env.create_release == 'true'
        uses: itsmeow/curseforge-upload@v3
        with:
          token: "${{ secrets.CURSEFORGE_TOKEN }}"
          project_id: "1537028"
          game_endpoint: "minecraft"
          game_versions: "Minecraft 26.1.2,Java 25,NeoForge"
          relations: "curios:requiredDependency,geckolib:requiredDependency,kotlin-for-forge:requiredDependency"
          file_path: "build/libs/cartridge-${{ env.version }}.jar"
          changelog: "${{ env.LAST_COMMIT_MESSAGE }}"

      - name: Upload to Modrinth
        if: env.create_release == 'true'
        uses: RubixDev/modrinth-upload@v1
        with:
          token: "${{ secrets.MODRINTH_TOKEN }}"
          project_id: "BjGfz7Td"
          name: "Cartridge v${{ env.version }}"
          version: "${{ env.version }}"
          game_versions: "26.1"
          loaders: "neoforge"
          featured: false
          relations: "vvuO3ImH:required,ordsPcFz:required,8BmcQJ2H:required"
          file_path: "build/libs/cartridge-${{ env.version }}.jar"
          changelog: "${{ env.LAST_COMMIT_MESSAGE }}"